### ISSUE TITLE
Permission Issues with Version 1.4.0

### ISSUE THREAD

**Issue by SuperGaleb** [tankmek/guacamole-docker-compose#1]
Hi,
I am having issues with guacamole:1.4.0 (version 1.3.0 works fine).

Version 1.4.0
7d2377f090bf   guacamole/guacamole:1.4.0         "/opt/guacamole/bin/…"   37 seconds ago   Restarting (1) 13 seconds ago
mkdir: cannot create directory ‘/home/guacamole/.guacamole’: Permission denied

Version 1.3.0:
fa6cacd04739   guacamole/guacamole:1.3.0         "/opt/guacamole/bin/…"   2 minutes ago   Up 2 minutes 
Any ideas ?
Thanks

**Comment by tankmek** [comment]
Hard to say with that output, you would have to give more context. What command did you use to generate that output? This has been up for some time so you have probably resolved this by now.
